version: "3"
services:
  proxy-center:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./mybin:/mybin
    command: /mybin/auto-reload-nginx.sh
